---
- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: restart ssh
  systemd:
    name: sshd
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: configure auto upgrades
  shell: dpkg-reconfigure -f noninteractive unattended-upgrades
